### ISSUE TITLE
API tests break when bumping org.flywaydb:flyway-core to v7

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#1052]
Let's understand why / fix the `org.flywaydb:flyway-core ` dependency bump to `v7.x.x`

**Comment by dakshin-k** [comment]
The public API for triggering migrations has [changed](https://github.com/flyway/flyway/commit/fc0f628a3b005b2026a01e7a0b88ec1c6699b6c4#diff-59e44f153051ce6261aa5ff0cb3120d6823dda25ddab4a3dccf12c0c1cfd806aR162) to return an object of type `MigrateResult` instead of an int.

Will raise a PR incorporating the change soon.
