### ISSUE TITLE
"Ambiguous Segment in URI" when trying to retrieve namespaces with "s3://" in it

### ISSUE THREAD

**Issue by APMoctezuma** [MarquezProject/marquez#1397]
Per OpenLineage [specifications](https://github.com/OpenLineage/OpenLineage/blob/main/spec/Naming.md#s3) a dataset coming from S3 should have a namespace in the form of `s3://<bucketname>`. This is working when it comes to publishing a run event  but when trying to retrieve a job or other information based on this namespace both endpoints of `/api/v1/namespaces/<namespace>` and `/api/v1-beta/lineage?nodeId=<dataset>:<namespace>:<name>` return a 400 error with the message "Ambiguous Segment in URI" when using the encoding of s3%3A%2F%2F for s3:// (since : and / are special characters I imagine we have to use encoding)

**Comment by dominiquetipton** [comment]
Since I looked into this a bit already I figured I'd leave my findings here. The issue specifically comes from the `%2F` (the `/` character) in the url. It seems Dropwizard and/or Jetty isn't allowing it because it can lead to potential security issues. However, I didn't have any issues with `%2F` being in a query string though (tested with Marquez 0.14.2).

**Comment by mobuchowski** [comment]
Seems like setting `httpCompliance: RFC2616_LEGACY` in marquez.yml is an workaround.

**Comment by mobuchowski** [comment]
Fixed by https://github.com/MarquezProject/marquez/pull/1419
