### ISSUE TITLE
Running built application doesn't expose any UI

### ISSUE THREAD

**Issue by kevingomezJC** [MarquezProject/marquez#1563]
I've built Marquez using `./gradlew build` and started running using `./gradlew :api:runShadow` and `java -Duser.timezone=UTC -jar marquez-*.jar server "${MARQUEZ_CONFIG}"` commands
I am able to use the client and `post`  data to our RDS instance, but running the application in this way doesn't expose any UI, wich is a problem since I want to see al the metadata from our RDS whitin the `web` module.
I've tried checking the UI running in port 5000 and 3000 but the UI seems not to be working (even though I can access to ports 8080 and 8081).
Does anyone know where to check the Marquez UI?
I'm runing this on a EC2 instance and had built the application following this link [https://github.com/MarquezProject/marquez#building](url)
And this are the logs from each command, I would be very grateful if someone tells me how to deploy Marquez in a productive way.
[build_marquez.log](https://github.com/MarquezProject/marquez/files/6941444/build_marquez.log)
[running_application.log](https://github.com/MarquezProject/marquez/files/6941452/running_application.log)
Thank you

**Comment by wslulciuc** [comment]
@kevingomezJC: The backend API and UI are run separately (as you pointed out in your issue). We do have docker images for the [`api`](https://hub.docker.com/repository/docker/marquezproject/marquez) and [`web`](https://hub.docker.com/repository/docker/marquezproject/marquez-web) as well as a pre-built [`jar`](https://search.maven.org/artifact/io.github.marquezproject/marquez-api/0.16.1/jar).

Since the backend API and UI are run separate, to run from source you would need to run the `jar`:

```
$ ./gradlew :api:runShadow
```

Then, for the UI, you'll need to override to specific the host and port for the Marquez backend (your values maybe different here). For example:

```
$ npm run build
$ MARQUEZ_HOST=localhost MARQUEZ_PORT=8080 node setupProxy.js
```

You should be able to browse to the UI at http://localhost:3000
