### ISSUE TITLE
Improve and Clarify the Marquez and OpenLineage clients experience

### ISSUE THREAD

**Issue by julienledem** [MarquezProject/marquez#1686]

**Comment by fm100** [comment]
Closed #1741 in favor of this.

We had an offline discussion about this and here's an update: We already have bunch of PRs for deprecating create APIs from Marquez, and having another API for OpenLineage from marquez side sounds weird, because it already implements the OpenLineage spec. We decided to update the README of Marquez client to make it clear that using OpenLineage client is preferred way to collect metadata.
