### ISSUE TITLE
Migrate Material UI version to v5

### ISSUE THREAD

**Issue by phixMe** [MarquezProject/marquez#1694]
The main UI package we use across our project has made some major changes with the new major release and has a long list of migration actions.

https://mui.com/guides/migration-v4/#update-react-amp-typescript-version

This includes
- [ ] Bumping the React Version
- [ ] Bumping the TS Version
- [ ] Migrate to Emotion from JSS
- [ ] Doing individual component modifications

**Comment by dakshin-k** [comment]
Hi @phixMe, I looked into picking this one up. Tried to upgrade to React 17 and ran into a couple problems:

- `react-vis` is [deprecated](https://github.com/uber/react-vis/blob/master/DEPRECATED.md) and doesn't support v17
- `react-helmet` [won't work with v17](https://github.com/nfl/react-helmet/issues/465) (Apparently the solution is to migrate to `react-helmet-async`?)

I'm not sure what to do about either of the above problems. Maybe they need to be separate issues that we should discuss and fix first?

Side note: I'm not sure what other problems we may face upgrading to v17, since at the moment I can't get past the `npm install` stage

**Comment by phixMe** [comment]
Hi @dakshin-k, thanks for looking into this.

I think we can actually drop `react-vis` as a dependency. It's actually not used as far as I can tell except adding a few stylesheets and TypeScript configuration.

 I think we should look into migrating to `react-helmet-async`. It should be a fairly simple task. 

I can create issues for both of these.

**Comment by phixMe** [comment]
@dakshin-k I've fixed both of the issues you've reported in the following PR. #2197

**Comment by dakshin-k** [comment]
Perfect! I'll try to raise a PR upgrading to React 17 over the next few days

**Comment by phixMe** [comment]
I think we should just move over to `jest` and `react-testing-library`. The tests should not be that difficult to migrate over since the project isn't too big. Many of the tests we had before have been removed already. 😄
