### ISSUE TITLE
Quickstart is broken, can't listen on port 5001

### ISSUE THREAD

**Issue by briansorahan** [MarquezProject/marquez#1715]
Here is what I'm seeing

```
./docker/up.sh --seed
Creating network "marquez_default" with the default driver
Creating marquez-db ... done
Creating marquez-api ... error

ERROR: for marquez-api  Cannot start service api: Ports are not available: listen tcp 0.0.0.0:5001: bind: address already in use

ERROR: for api  Cannot start service api: Ports are not available: listen tcp 0.0.0.0:5001: bind: address already in use
ERROR: Encountered errors while bringing up the project.
```

There is an easy fix that worked for me which is to let docker map 5000 and 5001 to ephemeral ports on the host.
It's still pretty easy to open the UI (the command is mac-specific but you get the idea)
```
open "http://localhost:$(docker-compose port api 5000 | sed 's;.*:;;')"
```

I'm happy to submit a PR if this seems reasonable ^

**Comment by wslulciuc** [comment]
@briansorahan: Sweet! Great to hear that the issue was resolved by using the `--api-port` and `--api-admin-port` flags.

> IMO having hardcoded ports in the documentation isn't ideal though, and a better approach is to just let docker assign ephemeral ports on the host.

When a [config file is not configured](https://github.com/MarquezProject/marquez/blob/main/docker/entrypoint.sh#L11), we run Marquez in `dev` mode using [`marquez.dev.yml`](https://github.com/MarquezProject/marquez/blob/main/marquez.dev.yml). The port values do have to be hardcoded, unfortunately. Knowing that, we decided to provide port override flags in `docker/up.sh`.

**Comment by wslulciuc** [comment]
@briansorahan, closing as you we're able to get up and running with Marquez 🚀
