### ISSUE TITLE
turn on JDBI sql monitoring

### ISSUE THREAD

**Issue by sshah-wework** [MarquezProject/marquez#182]
See: https://metrics.dropwizard.io/3.1.0/manual/jdbi/

**Comment by hougs** [comment]
`.setTimingCollector(TimingCollection TC)` has been deprecated in JDBI in favor of `.setSqlLogger(SqlLogger SL)`
The choice is between:
1) using what is described in the link provided, which is deprecated usage of `.setTimingCollector`
2) depending on of [io.dropwizard.metrics:metrics-jdbi:4.1.0-rc3.](https://github.com/dropwizard/metrics/commit/097adc30a94d253237c330f7e34b9617d8e7a9b2#diff-5071f08f185213b9eee1192ea046a7d1)

I think it is a pretty low risk dependency and I'm inclined to have us depend on rc-3 because that wil mean minor changes in the future and not being *one of those people* who continues to use deprecated methods. Thoughts?

**Comment by wslulciuc** [comment]
Sure. Sounds like a reasonable approach to me! Thanks for looking into this @hougs

**Comment by wslulciuc** [comment]
Issue addressed in #241
