### ISSUE TITLE
Choose non-default port for Postgres in docker/up.sh

### ISSUE THREAD

**Issue by rossturk** [MarquezProject/marquez#1956]
I keep running into situations where I want to run Marquez alongside Airflow (or another system that also runs a Postgres database) and the two docker-compose environments both attempt to start a Postgres database. The "correct" workaround is to create a single docker-compose environment with a shared database for both systems, but this is not always ideal.

It would be nice if we could tell `docker/up.sh` to start Postgres on an alternate port.

**Comment by collado-mike** [comment]
TBH, there's not a lot of reason to map the database port to any specific port on the host. The Marquez API will get routed by Docker to whatever port it's actually bound to. The only useful thing we get out of mapping to a specific port is that we can use `psql` on the command line to query the database during development. `docker port marquez-db 5432` is all we really need to find what port to connect to, though

**Comment by rossturk** [comment]
It's not about accessing the DB, it's about other tools complaining that they can't start their own databases because the port is in use.

**Comment by collado-mike** [comment]
Yeah, I got it. I'm saying there will be no conflicts if we bind `5432` to a _random_ port (if we change [this](https://github.com/MarquezProject/marquez/blob/main/docker-compose.yml#L37) line to just `5432` instead of `5432:5432`).

The API container will still be able to hit the database because docker magic will translate `db:5432` to whatever actual port it's bound to. Only commands outside the docker network will have problems (i.e., `psql` on the command line), but that can be addressed with the `docker port` command.
