### ISSUE TITLE
Docker up script fails if parent folder is not named "marquez"

### ISSUE THREAD

**Issue by rossturk** [MarquezProject/marquez#2382]
To save typing, I check out the Marquez repo into a folder called `mqz`:

```
git clone git@github.com:marquezproject/marquez.git mqz
```

I noticed that on the systems where I do this, I can't get the `docker/up.sh` script to complete successfully. If I check it out into a folder called `marquez`, it works.

Here's a video where I reproduce this issue:

https://user-images.githubusercontent.com/1434475/214937591-c20155f7-c95c-42fc-ba05-d9a8880e29fa.mov

**Comment by seanmullane** [comment]
Can confirm this is still an ongoing issue

**Comment by wslulciuc** [comment]
In `docker/up.sh`, we change to the project root directory with:
```
# Change working directory to project root
project_root=$(git rev-parse --show-toplevel)
cd "${project_root}/"
``` 

When the run `$(git rev-parse --show-toplevel)` locally for the project root:

```
/Users/wsl/dev/io.marquezproject/mqz
```

This issue is we [hardcode](https://github.com/MarquezProject/marquez/blob/main/docker/up.sh#L160) the docker volume prefix to `marquez` in stead of using the base directly of `project_root`.
