### ISSUE TITLE
UI error: max call stack size exceeded

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#2410]
<img width="507" alt="Screen Shot 2023-02-03 at 4 16 40 PM (1)" src="https://user-images.githubusercontent.com/1553185/217618061-2a4c3f55-2b9d-4c41-9799-dfd035da5477.png">

**Comment by harels** [comment]
@wslulciuc do we have some more details here to help repro the issue?

**Comment by jlukenoff** [comment]
I'm getting this error as well. Seems to be coming from this [line of code](https://github.com/MarquezProject/marquez/blob/f9465bf4d2a5c783b1bc88378983667b3b1465df/web/src/components/lineage/Lineage.tsx#L152) getting called recursively and blowing the stack.

![image](https://github.com/MarquezProject/marquez/assets/36255627/8239e60b-7ab7-43dc-9386-abfc7823eda9)

I'm investigating to see if this dataset has a large amount of upstream nodes or something but I don't expect that to be the case.

**Comment by jlukenoff** [comment]
I took a deeper look into this and it seems like the inner helpers in `getSelectedPaths` ([ref](https://github.com/MarquezProject/marquez/blob/f9465bf4d2a5c783b1bc88378983667b3b1465df/web/src/components/lineage/Lineage.tsx#L143-L174)) aren't handling graph cycles well. It feels like this would be better to do iteratively rather than recursively or some better base case should be added to prevent stack overflow. Happy to open a PR for this
