### ISSUE TITLE
Service models must not include a UUID field

### ISSUE THREAD

**Issue by ashulmanWeWork** [MarquezProject/marquez#363]
For consistency, a UUID field should be included on all object models. For example, `service.models.Job` (and most others) contains a UUID field, but `service.models.Dataset` does not.

**Comment by wslulciuc** [comment]
The UUIDs set in our service models reference the primary key of a given row and should be removed. It's something I've been meaning to address. We now map individual rows to a **db** [row](https://github.com/MarquezProject/marquez/tree/master/src/main/java/marquez/db/models) instead of a service model.

So, it's not about consistency but rather code we never got around to cleaning up

**Comment by wslulciuc** [comment]
I'll work on defining a set of clean up tasks for our service models

**Comment by wslulciuc** [comment]
Fixed #627
