### ISSUE TITLE
add query parameters to list endpoints to enable testing for existence

### ISSUE THREAD

**Issue by sshah-wework** [MarquezProject/marquez#424]
The short-term plan for idempotency is suppress creation of duplicates silently and return the ID of the original object. Long term, we want to add query parameters to the list endpoints so that clients can test if something exists before attempting to create via a `POST` to the API.

Each list endpoint will support filtering by different parameters -- at the very least, supporting filtering by fields which define uniqueness (e.g. `name` is a unique field for jobs, so filtering by `name` in the `/.../jobs` list endpoint should be possible)

**Comment by pbrahmbhatt3** [comment]
Hi! can I work on it?

**Comment by wslulciuc** [comment]
Hey, @pbrahmbhatt3! We'd love your help, but before we can begin mapping filterable parameters to query parameters in our APIs, we'll need to expand on the idea a bit more. For context, this issue was opened to capture an offline discussion our team had around the semantics of our HTTP status codes and idempotency of certain API calls. We'll first want to define an epic outlining the reason for the change and properly scope the work. We plan to add more details around this feature soon.
